### ISSUE TITLE
Updated README

### ISSUE THREAD

**Issue by sarbbottam** [ta2edchimp/opt-cli#13]
Fix typo at 

```
"ghooks": {
  "precommit": "...", // should be pre-commit
  ...
}
```

May be the usage could be explained a bit more precisely, best would to point to an example project.

**Comment by sarbbottam** [comment]
BTW, I can take this up tomorrow.

**Comment by ta2edchimp** [comment]
Thanks for pointing this out and reporting back.
Example projects could be `ghooks` and `eslint-find-new-rules`.

PR welcome :wink: 
(Would not come up with something myself until later today eu tz).

**Comment by sarbbottam** [comment]
Quick question:
- What if I want to opt-in to multiple rules? Should I have multiple lines in the `opt-in` file?

```
cat opt-in
rule1
rule2
```
- Can I add a comment to the `opt-in` file?
- for `opt-out` as in `"ghooks": { "pre-push": "opt --out pre-push --exec \"make lint\""}`, how does the user **opt out** of the rule? I don't think I comprehend the following.
  
  > > If you specify an opt --out then you MUST NOT have the string specified in the .opt-out file or in your package.json's config.opt.out
- If there are multiple `opt-out` rules and the user wants to **opt out** for few, how does the user do that?

Thanks!!

**Comment by ta2edchimp** [comment]
I got to thank you for pointing out all these things!

---

#### 1. What if I want to opt-in to multiple rules? Should I have multiple lines in the `opt-in` file?

> ```
> cat opt-in
> rule1
> rule2
> ```

Yes, exactly this.

Within an `.opt-in` (or `.opt-out`) file you address multiple rules by adding multiple lines, one line per rule (see [test fixture for an `.opt-in`](https://github.com/ta2edchimp/opt-cli/blob/master/test/fixtures/opt-files/.opt-in)).
When using the `package.json`'s `config` field of a project that depends upon `opt-cli`, multiple rules may be addressed by adding an item for each rule to an array, called either `in` or `out` (see [test fixture for `package.json`](https://github.com/ta2edchimp/opt-cli/blob/master/test/fixtures/package/package.json)).

---

#### 2. Can I add a comment to the opt-in file?

I'm working on this right now and will publish it later today. File content could then look like this:

```
# This is a random example opt-in rule
random-rule-one

# This is another random example opt-in rule
# Remove the comment to opt-in to that rule
# random-rule-two
```

---

#### 3. for `opt-out` as in `"ghooks": { "pre-push": "opt --out pre-push --exec \"make lint\""}`, how does the user **opt out** of the rule? I don't think I comprehend the following.

> > > If you specify an opt --out then you MUST NOT have the string specified in the .opt-out file or in your >>>package.json's config.opt.out

Hmm... I try to explain as follows:

**opt-in**

```
opt --in {opt-in-rule} --exec {command}
```

`{command}` will only be executed, when the `.opt-in` file is present, containing a line with `{opt-in-rule}`.

**opt-out**

```
opt --out {opt-out-rule} --exec {command}
```

`{command}` will be executed, **unless** the `.opt-out` file is present, containing a line with `{opt-out-rule}`.

So, for the example above:

```
"ghooks": { "pre-push": "opt --out pre-push --exec \"make lint\""}
```

`make lint` will be executed, **unless** there is an `.opt-out` file present, containing a line with `pre-push`.

---

#### 4. If there are multiple `opt-out` rules and the user wants to _opt out_ for few, how does the user do that?

As with `opt-in` rules, rules to opt-out from are to be put (one per line) into a `.opt-out` file. Or, each as a string element, into an `out` array within `package.json`'s `config.out` field.

**Comment by ta2edchimp** [comment]
Comments in `.opt-in` and `.opt-out` files are now supported as of v1.2.0 ( #15 ):

Example:

```
# This is a comment
foo-rule
bar-rule

# The following is a
# commented out rule
#baz-rule
```

Rules to be taken into account are `foo-rule` and `bar-rule`.

**Comment by sarbbottam** [comment]
@ta2edchimp awesome, I guess my queries are answered.

> > Example projects could be ghooks and eslint-find-new-rules.
> > I guess its partially true, as the `.opt-in` and `opt-out` will be `.gitignore`d. So examples, with those file checked in would be very helpful.

I guess `opt-in` is not limited to `ghooks`, but one could use it in [`npm scripts`](https://docs.npmjs.com/misc/scripts) too.

I would raise the PR in the evening.

**Comment by ta2edchimp** [comment]
> I guess `opt-in` is not limited to `ghooks`, but one could use it in `npm scripts` too.

Yep, as long as it is run within an `npm scripts` context in general (as are the git hooks managed by `ghooks`), it does.

I also noticed, `opt-cli` also makes for a handy little tool globally available in one's shell, when installed globally (`npm i -g opt-cli`) :grin:
