### ISSUE TITLE
Set the `$PATH` to include `node_modules`

### ISSUE THREAD

**Issue by kentcdodds** [ta2edchimp/opt-cli#7]
From https://github.com/gtramontina/ghooks/pull/51

> I think that the command is not executed with the proper `$PATH` because I don't think that it can find `validate-commit-msg` which is in `node_modules/.bin/` which [we add](https://github.com/gtramontina/ghooks/blob/5ac56bf5869cc1dd69db6dad83ae6cbcf1dac0aa/lib/runner.js#L31-L33) to the path when [we run our scripts](https://github.com/gtramontina/ghooks/blob/5ac56bf5869cc1dd69db6dad83ae6cbcf1dac0aa/lib/runner.js#L34)

**Comment by ta2edchimp** [comment]
Thanks for reporting I'll have a look into this during the day.
I have no clue anymore, why I used the cli lib's exec method anyway, as I planned to use something like ghooks runner as a template in the first place (same for #6); must have been simply too late for me ...
